const notiType = {
	NEWS: "NEWS",
	DISCOUNTS: "DISCOUNTS",
	UPDATE_INFO: "UPDATE_INFO",
	CONFIRM_ACCOUNT: "CONFIRM_ACCOUNT",
	HEALTH_FAMILY_ALERT: "HEALTH_FAMILY_ALERT",
	REVIEW_UPLOAD: "REVIEW_UPLOAD",
	TOPIC_NEW_QUESTION: "TOPIC_NEW_QUESTION",
	TOPIC_REPLY: "TOPIC_REPLY",
	TOPIC_CONFIRM: "TOPIC_CONFIRM",
	TOPIC_REJECT: "TOPIC_REJECT",
	TOPIC_INTEREST_SPECIALTY: "TOPIC_INTEREST_SPECIALTY",
	REMINDER_MEASURE: "REMINDER_MEASURE",
	SUPERVISOR_REQUEST: "SUPERVISOR_REQUEST",
	SUPERVISED_REQUEST: "SUPERVISED_REQUEST",
	SUPERVISOR_ACTIONS: "SUPERVISOR_ACTIONS",
	APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
	APPOINTMENT_EXPIRE: "APPOINTMENT_EXPIRE",
	APPOINTMENT_ACCEPT: "APPOINTMENT_ACCEPT",
	APPOINTMENT_REJECT: "APPOINTMENT_REJECT",
	APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",
	APPOINTMENT_PATIENT_CANCEL: "APPOINTMENT_PATIENT_CANCEL",
	APPOINTMENT_PATIENT_CHANGE: "APPOINTMENT_PATIENT_CHANGE",
	APPOINTMENT_DOCTOR_CHANGE: "APPOINTMENT_DOCTOR_CHANGE",
	APPOINTMENT_FAILED_TO_NURSE: "APPOINTMENT_FAILED_TO_NURSE",
	ALARM_UPDATE: "ALARM_UPDATE",
	PATIENT_FAMILY_REQUEST: "PATIENT_FAMILY_REQUEST",
	PATIENT_FAMILY_ACCEPT: "PATIENT_FAMILY_ACCEPT",
	PATIENT_FAMILY_REJECT: "PATIENT_FAMILY_REJECT",
	PATIENT_FAMILY_DELETE: "PATIENT_FAMILY_DELETE",

	NURSE_SHIFT_CREATED: "NURSE_SHIFT_CREATED",
	NURSE_SHIFT_UPDATED: "NURSE_SHIFT_UPDATED",
	NURSE_SHIFT_REMOVED: "NURSE_SHIFT_REMOVED",
	NURSE_SHIFT_ADD_MEMBER: "NURSE_SHIFT_ADD_MEMBER",
	NURSE_SHIFT_REMOVE_MEMBER: "NURSE_SHIFT_REMOVE_MEMBER",
	NURSE_SHIFT_REMINDER: "NURSE_SHIFT_REMINDER",
	DOCTOR_CALL_NOT_EVALUATE_REMINDER: "DOCTOR_CALL_NOT_EVALUATE_REMINDER",

	DOCTOR_FAVORITE_UPDATE_FREETIME: "DOCTOR_FAVORITE_UPDATE_FREETIME",
}

const topicType = {
	SUPERVISOR_ACTIONS: "SUPERVISOR",
	FORUMS: "FORUMS",
	PATIENT_FAMILY_ACTIONS: "PATIENT_FAMILY",
}


module.exports = {
	notiType,
	topicType
}